name: App buid

on:
  push:
    branches:
      - dev
      - test
      - prod

env:
  BUILD_NAME: "${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}"
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set FULL_BUILD_NAME
        id: extract-full-build-name
        run: |
          FULL_BUILD_NAME=$BUILD_NAME:${{ github.sha }}
          echo "FULL_BUILD_NAME=$FULL_BUILD_NAME" >> $GITHUB_ENV

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract full build name
        shell: bash
        run: echo "full_build_name=$FULL_BUILD_NAME" >> $GITHUB_OUTPUT
        id: full_build_name

      - name: check Build name
        run: echo '${{ steps.extract_build_name.outputs.build_name }}'

      - name: Create .env file dev
        if: steps.extract_branch.outputs.branch == 'dev'
        run: |
          echo "REACT_APP_BASE_URL=${{ vars.DEV_BE_BASE_URL }}" >> .env

      - name: Create .env file test
        if: steps.extract_branch.outputs.branch == 'test'
        run: |
          echo "REACT_APP_BASE_URL=${{ vars.TEST_BE_BASE_URL }}" >> .env

      - name: Create .env file prod
        if: steps.extract_branch.outputs.branch == 'prod'
        run: |
          echo "REACT_APP_BASE_URL=${{ vars.PROD_BE_BASE_URL }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: check env
        run: cat .env

      - name: Build Docker image
        run: docker build -t $FULL_BUILD_NAME .

      - name: Push Docker image
        run: docker push $FULL_BUILD_NAME

      - name: Set up global config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: clone FluxCD
        run: |
          git clone https://github.com/ArthurF-java/flux-cd.git

      - name: Update FluxCD deployment.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'flux-cd/fe/${{ steps.extract_branch.outputs.branch }}/deployment.yaml'
          changes: |
            {
              "spec.template.spec.containers[0].image": "${{ steps.full_build_name.outputs.full_build_name }}"
            }
          commitChange: false

      - name: Push to FluxCD repository
        run: |
          cd flux-cd
          git add --all
          git commit -m "${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}"
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/arthurf-java/flux-cd.git main
#
      - name: Slack Notification Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-check
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: 'Deploy FE is done for image 1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-error
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: 'Deploy FE is failed for image 1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
